apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    role: mysql
spec:
  containers:
  - name: mysql
    image: 344625735300.dkr.ecr.us-east-1.amazonaws.com/mysql:v1.0
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "os"
  imagePullSecrets:
  - name: regcred
