apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: mywebapp
        image: 344625735300.dkr.ecr.us-east-1.amazonaws.com/mywebapp:v1.0
        ports:
        - containerPort: 8080
        env:
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: DBPORT
          value: "3306"
        - name: DBHOST
          value: "10.244.0.10"
        - name: APP_COLOR
          value: "blue"
      